### ISSUE TITLE
Generalize "spesen" and "airplus" config into "regular"

### ISSUE THREAD

**Issue by bebbi** [bebbi/taloc-loader#35]
Airplus and Archive follow the same format, no need to separate them - adjust code and config.

**Comment by abhishekmaha23** [comment]
I think this is currently how it works in the code!
Code changes would be only in run.py? (only the segment to concat the data)

**Comment by bebbi** [comment]
I agree, this can probably be closed

**Comment by bebbi** [comment]
@abhishekmaha23  This issue is about the following:

Current config.yml:

```
legs:
  spesen:
    - '[Spesen_flights.xlsx]Tabelle1'
  airplus:
    - '[Airplus_flights.xlsx]Tabelle1'
  bta:
    - '[bta_flights.xlsx]Tabelle1'
```

Desired config.yml:

```
legs:
  regular:
    - '[Spesen_flights.xlsx]Tabelle1'
    - '[Airplus_flights.xlsx]Tabelle1'
  bta:
    - '[bta_flights.xlsx]Tabelle1'
```

--> There should even be no difference for spesen/airplus even in run.py
